coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 2%
    patch:
      default:
        target: 50%

comment:
  layout: "header, diff, flags, components"
  behavior: default

flags:
  backend:
    paths:
      - backend/
  ml:
    paths:
      - src/
  frontend:
    paths:
      - frontend/
